### ISSUE TITLE
Tracking files and movements

### ISSUE THREAD

**Issue by Simonepiano01** [GamingBunker/AnimePlex#12]
# Tracking files inside the Plex library folders
I think that a micro-service could be added, that silently monitors files inside the Plex library folder.

The service should do the following:
- Check if the path that is saved in the database (for the various episodes) is still valid, and the episode is still there (by hash)
- If the video file is not where it should be, the service should look at the library and search for the episode by hashing the files and comparing the hash with the one that is registered in the DB for that episode.
- When the hash has been found, the service needs to update the path in the DB, so every other service that needs to access the episode have the updated location.

Of course the first time an episode is downloaded, the hash and the first path should get immediately noted on the database, so when this new service start's checking integrity of the library, it knows what to look for.

I suggest naming it something like "validator" or "integritychecker" (of course this are suggestions 😂).

A service like this can be used to check all sorts of things not only file locations and paths ...

**Comment by cesxhin** [comment]
Thank you for this great idea!
Some day there will be an update with tracking files!
